language: node_js
sudo: required
services:
  - docker
node_js:
  - "6"
  - "7"
before_install:
  - bash ./start
script:
  - bash ./test
notifications:
  email: false
after_success:
  - ./node/node_modules/.bin/codecov
