proxy:
#  restart: always
  build: ./proxy
  ports:
    - 80:80
    - 443:443
  links:
    - web
    - api
web:
  build: ./web
  ports:
    - 5000:5000
  links:
    - db
api:
  build: ./api
  ports:
    - 3000:3000
  links:
    - db
db:
  build: ./db
  ports:
    - 6379:6379
