proxy:
#  restart: always
  build: ./proxy
  ports:
    - 80:80
    - 443:443
  links:
    - app1
    - app2
    - app3
app1:
  build: ./app
  links:
    - db
app2:
  build: ./app
  links:
    - db
app3:
  build: ./app
  links:
    - db
db:
  build: ./db
