proxy:
#  restart: always
  build: ./proxy
  ports:
    - 80:80
    - 443:443
  links:
    - php
    - node
  volumes:
    - ./php:/var/www/html
php:
  build: ./php
  ports:
    - 9000
  links:
    - data
node:
  build: ./node
  ports:
    - 3000
  links:
    - data
data:
  build: ./data
  volumes:
    - /data/redis:/data
  ports:
    - 6379
