nginx:
  restart: always
  build: nginx    
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /www/public
  volumes_from: 
    - usr/src/app
  links:
    - app:app
app:
  build: app
  ports:
    - "3000:3000"
  volumes:
    - usr/src/app:usr/src/app
  links:
    - redis 
redis:
  image: redis
