proxy:
#  restart: always
  build: ./proxy
  ports:
    - 80:80
    - 443:443
  links:
    - web
    - api
web:
  build: ./web
  ports:
    - 9000:9000
  links:
    - data
api:
  build: ./api
  ports:
    - 3000:3000
  links:
    - data
data:
  build: ./data
  volumes:
    - /data/redis:/data
  ports:
    - 6379:6379
