nginx:
  restart: always
  build: ./nginx
  ports:
    - 80:80
    - 443:443
  links:
    - node
node:
  build: ./node
  ports: 
    - 3000:3000
  links:
    - redis
redis:
  build: ./redis
  ports: 
    - 6379:6379
