version: '2'

services:
    proxy:
        image: dockercloud/haproxy:1.6.2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:bind
        ports:
            - 80:80     # http
            - 1936:1936 # stats
        environment:
            - "constraint:node.role==manager"
            - mode=global
            - STATS_AUTH="admin:admin"
        networks:
            - net-local
            - net-public
    chat:
        image: 192.168.99.100:5000/chat:latest
        ports:
            - "3000"
        environment:
            - "constraint:node.role!=manager"
            - REDIS_IP=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        networks:
            - net-local

    redis:
        image: redis:3.2.6
        container_name: data-redis
        volumes:
            - data-redis:/data
        ports:
            - "6379"
        environment:
            - "constraint:node.role!=manager"
        networks:
            - net-local

volumes:
    data-redis:
        driver: local

networks:
    net-local:
        driver: overlay
        ipam:
            config:
                - subnet: 10.0.9.0/24
    net-public:
        driver: overlay
        ipam:
            config:
                - subnet: 10.0.9.0/24
