version: '2'

services:
    proxy:
        image: 172.16.110.141:5000/dockercloud/haproxy:1.6.2
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        environment:
            - MODE=swarm
        depends_on:
            - app-chat
        networks:
            - net-public

    chat:
        image: 172.16.110.141:5000/chat:0.0.0
        ports:
            - 3000
        environment:
            - "constraint: node.role != manager"
            - PORT=3000
            - REDIS_IP=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        networks:
            - net-local
            - net-public

    redis:
        image: 172.16.110.141:5000/redis:0.0.0
        container_name: data-redis
        volumes:
            - data-redis:/data
        ports:
            - 6379
        environment:
            - PORT=6379
        networks:
            - net-local

volumes:
    data-redis:
        driver: local

networks:
    net-local:
    net-public:
