nginx:
  restart: always
  build: ./nginx
  ports:
    - 80:80
  links:
    - node1
    - node2
    - node3
node1:
  build: ./node
  ports: 
    - 3000
  links:
    - db
node2:
  build: ./node
  ports: 
    - 3000
  links:
    - db
node3:
  build: ./node
  ports: 
    - 3000
  links:
    - db
db:
  image: redis:3.2.5
  ports: 
  - 6379
