proxy:
#  restart: always
  build: ./proxy
  ports:
    - 80:80
    - 443:443
  links:
    - web
    - admin
    - api
web:
  build: ./web
  links:
    - db
admin:
  build: ./admin
  links:
    - db
api:
  build: ./api
  links:
    - db
db:
  build: ./db
