nginx:
#  restart: always
  image: nginx:1.11.6
  container_name: nginx  
  volumes:
    - ./proxy/vhost.d:/etc/nginx/vhost.d
  ports:
    - 80:80
    - 443:443
proxy:
  image: jwilder/docker-gen:0.7.3
  container_name: proxy
  command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  links:
    - php
    - node

php:
  build: ./php
  container_name: php
  ports:
    - 9000:9000
  environment: 
    - VIRTUAL_HOST=rnd.asiantech.vn
  links:
    - data
  volumes: 
    - /cache/php:/cache/php

node:
  build: ./node
  container_name: node
  ports:
    - 3000:3000
  environment: 
    - VIRTUAL_HOST=api.rnd.asiantech.vn
  links:
    - data
  volumes: 
    - /cache/node:/cache/node

data:
  build: ./data
  container_name: data
  volumes:
    - /data/redis:/data
  ports:
    - 6379:6379
