version: '1.0.0'
services:
  nginx:
    build: nginx    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /public
    volumes_from: 
      - app    
    links:
      - app:app
    restart: always
  app:
    build: app
    ports:
      - "3000:3000"
    volumes:
      - app:/app
    links:
      - redis
    depends_on:
      - db
      - nginx    
  redis:
    image: redis
  db:
    image: mongodb
